### ISSUE TITLE
Improve design space for relaxation parameters

### ISSUE THREAD

**Issue by gouarin** [pylbm/pylbm_ui#3]
For now, even if we choose sigma notation and log, the min and max of the relaxation parameters are then computed from these inputs and the sampling is done after.

It will be better to make the sampling of the min and max given by the user and then recompute the relaxation parameters.

**Comment by ThibautVanHoof** [comment]
True, the final objective of log and sigma is to sample the relaxation parameters ('s') in a non uniform manner in order to focus on the region close to 2 (low diffusion). It is an important feature, especially for the analysis of inviscid (Euler) scheme, or in case of aero flows with low gas viscosity.
 
The 's' range is [0,2]. To obtain a non uniform sampling with more dense distribution close to s=2, the two proposed steps are:
     1. use sigma=1/s-0.5 with new range [inf, 0] . Moreover sigma is somehow related to the diffusion in reduced lattice units (dx=dt=1) with sigma=0 meaning zero diffusion
     2. use a log10(sigma) as the parameter to be sampled with a range selected by the user inside the full validity region [inf, -inf]. Zero diffusion (s=2) is approached for log10(sigma) tending toward -inf

Note that the current implementation allows to use log10(s) as parameter which is not very convenient since it range between [-inf, 0.3]. It is less flexible/intuitive to sample low diffusion region than log10(sigma).

**Comment by gouarin** [comment]
implemented in 25688fabdb08c9a1f6ba123ca12485149b7b4ca5

**Comment by ThibautVanHoof** [comment]
Thanks Loic.

But it looks like the current version of parametric study has strange behaviors (f3189e3) . Log is ok for relax parameters but seems also applied to lambda leading to values smaller than  the requested bounds. Most of the diffusions values are negative, CFL is NaN and stability is True  even if the input data are obviously wrong (probably due to single simulation step due to lambda << 1?). See the screenshot below: 
 
![Screenshot from 2021-05-25 12-09-16](https://user-images.githubusercontent.com/57364219/119480787-4ce55d00-bd52-11eb-8bce-d77a5806ddf2.png)

Note that this version has been tested on Binder. The local install lead to the following errors:

------------------
from pylbm_ui.voila_main import main
------------------

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/anaconda3/envs/pylbm_ui/lib/python3.8/pkgutil.py in get_importer(path_item)
    414     try:
--> 415         importer = sys.path_importer_cache[path_item]
    416     except KeyError:

KeyError: PosixPath('/home/vanhoof/T6Codes/LBM/LBMHYPE/Git_pylbm_ui/pylbm_ui/schema')

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<ipython-input-2-99708c7e8018> in <module>
----> 1 from pylbm_ui.voila_main import main

~/T6Codes/LBM/LBMHYPE/Git_pylbm_ui/pylbm_ui/pylbm_ui/voila_main.py in <module>
     10 
     11 import ipyvuetify as v
---> 12 from .widgets import *
     13 
     14 from schema import cases

~/T6Codes/LBM/LBMHYPE/Git_pylbm_ui/pylbm_ui/pylbm_ui/widgets/__init__.py in <module>
     11 from .stability import StabilityWidget
     12 from .simulation import SimulationWidget
---> 13 from .parametric_study import ParametricStudyWidget
     14 from .post_treatment import PostTreatmentWidget
     15 from .pylbmwidget import out

~/T6Codes/LBM/LBMHYPE/Git_pylbm_ui/pylbm_ui/pylbm_ui/widgets/parametric_study.py in <module>
     20 
     21 from .debug import debug
---> 22 from .design_space import DesignWidget
     23 from .dialog_path import DialogPath
     24 from .discretization import dx_validity

~/T6Codes/LBM/LBMHYPE/Git_pylbm_ui/pylbm_ui/pylbm_ui/widgets/design_space.py in <module>
     14 from traitlets import Unicode, Float, List, Bool
     15 
---> 16 from schema.utils import SchemeVelocity, RelaxationParameterFinal
     17 
     18 from .debug import debug

~/T6Codes/LBM/LBMHYPE/Git_pylbm_ui/pylbm_ui/schema/__init__.py in <module>
      8 from .utils import define_cases
      9 
---> 10 cases = define_cases(__file__, __name__)

~/T6Codes/LBM/LBMHYPE/Git_pylbm_ui/pylbm_ui/schema/utils.py in define_cases(filename, modulename)
     42     gbl = globals()
     43     package_dir = Path(filename).resolve().parent
---> 44     for _, module_name, ispkg in iter_modules([package_dir]):
     45         if ispkg:
     46             module = f"{modulename}.{module_name}"

~/anaconda3/envs/pylbm_ui/lib/python3.8/pkgutil.py in iter_modules(path, prefix)
    127 
    128     yielded = {}
--> 129     for i in importers:
    130         for name, ispkg in iter_importer_modules(i, prefix):
    131             if name not in yielded:

~/anaconda3/envs/pylbm_ui/lib/python3.8/pkgutil.py in get_importer(path_item)
    417         for path_hook in sys.path_hooks:
    418             try:
--> 419                 importer = path_hook(path_item)
    420                 sys.path_importer_cache.setdefault(path_item, importer)
    421                 break

~/anaconda3/envs/pylbm_ui/lib/python3.8/importlib/_bootstrap_external.py in path_hook_for_FileFinder(path)

~/anaconda3/envs/pylbm_ui/lib/python3.8/importlib/_bootstrap_external.py in __init__(self, path, *loader_details)

~/anaconda3/envs/pylbm_ui/lib/python3.8/importlib/_bootstrap_external.py in _path_isabs(path)

AttributeError: 'PosixPath' object has no attribute 'startswith'
AttributeError: 'PosixPath' object has no attribute 'startswith'

**Comment by gouarin** [comment]
The binder issue should be fixed in https://github.com/pylbm/pylbm_ui/pull/17. Could you confirm?

For the other issue, I have no idea. I will take a look.

**Comment by ThibautVanHoof** [comment]
The log sampling of sigma works now. Thanks Loic!

However, it is not possible to plot the log(Sigma) using the PCP. Only the values of the relaxation rate can be plotted -> the interesting behavior occurring over several order of magnitude of sigma can be sampled but not observed with the PCP.  To illustrate the issue, look at the PCP obtained using the current pylbm_ui version (purple to yellow colormap) Vs the PCP using the LBMHYPE prototype (blue to red colormap) where a clear threshold in log(sigma) appearing.
![PCP_logSigma](https://user-images.githubusercontent.com/57364219/119801737-4683ec00-bede-11eb-9542-80bb26c145a3.png)
![PCP_logSigma_LBMHYPEprototype](https://user-images.githubusercontent.com/57364219/119801772-4b48a000-bede-11eb-8525-43db4202819d.png)
That's a new issue but the topic is closely related to the current log sampling issue so I put it here. 

Note that PS could be very slow using Binder (depending of the executing machine I suppose?). Moreover, Binder automatically deconnect after some minutes of inactivity and the whole PS need to be re-run... Local run should be far more comfortable for both testing and real applications.

**Comment by ThibautVanHoof** [comment]
seems fixed in 4efcef4063f52adb9facbbc3e3324623cf8efaab.
